- include: name.yml
- include: email.yml

- name: Set git config
  git_config:
    name: "{{ item.name }}"  
    scope: global
    value: "{{ item.value }}"  
  with_items:    
    - {name: "core.editor",  value: "code --wait"}    
    - {name: "merge.tool", value: "vscode"}
    - {name: "mergetool.vscode.cmd", value: "code --wait $MERGED"}
    - {name: "diff.tool", value: "vscode"}
    - {name: "difftool.vscode.cmd", value: "code --wait --diff $LOCAL $REMOTE"}
    - {name: "core.excludesfile", value: "{path-to-home-dir}/.gitignore"}