# goooseman staff
- hosts: all
  roles:
    - common/kubectl
    - osx/kops
    - common/rvm

- hosts: all
  roles:
    - common/gitconfig
    - common/fnm
    - common/robo3t
    - common/reactotron
- hosts: all
  tasks:
    - name: install homebrew casks apps
      homebrew_cask:
        name:
          - postman
          - sublime-text
          - sublime-merge
          - docker
          - android-studio
        state: present

- hosts: all
  tasks:
    - name: install homebrew packages
      homebrew:
        name:
          - git-flow-avh
          - micro
          - wifi-password
          - bat
          - ripgrep
          - autojump
        state: present

- name: Change user shell to zsh
  user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh

- hosts: all
  roles:
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_env.USER }}"
          visual_studio_code_extensions:
            - eamodio.gitlens
            - dbaeumer.vscode-eslint
            - ms-vscode.vscode-typescript-tslint-plugin
            - esbenp.prettier-vscode
          visual_studio_code_settings: {
            "editor.rulers": [80, 100, 120],
            "workbench.editor.enablePreview": false,
            "editor.fontFamily": "Fira Code",
            "editor.fontLigatures": true,
          }