- hosts: all
  roles:
    - ubuntu/zsh
    - pi/usbmount
    - pi/docker
    - pi/aria2
    - pi/plex

- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Turn off ssh by password auth
      lineinfile:
        destfile: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
    - name: Turn off ssh for root user
      lineinfile:
        destfile: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
    - name: Install a list of packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - connectd
    - name: Install a list of locales
      locale_gen:
        name: "{{ locales }}"
        state: present
      vars:
        locales:
        - en_US.UTF-8
        - ru_RU.UTF-8
        - he_IL.UTF-8