- hosts: all
  roles:
    - common/chezmoi
    - ubuntu/zsh

- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Turn off ssh by password auth
      lineinfile:
        destfile: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
    - name: Turn off ssh for root user
      lineinfile:
        destfile: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'