# Playbook to install tinc server on some remote server and tinc on raspberry pi
# It shares public keys to make the clients to communicate to each others

- hosts: cloud
  sudo: yes
  remote_user: root
  gather_facts: no
  tasks:
    - name: "Install python2"
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - python-setuptools
          - python
          - python-pip
    
- hosts: cloud
  vars:
    tincvpn_nodename: cloud
    tincvpn_destination: cloud
  roles:
    - pi/tinc
  tasks:
    - name: Run tcp proxy
      docker_container:
        name: pi-proxy
        image: tecnativa/tcp-proxy
        restart: yes
        restart_policy: always
        ports:
          - "5000:5000"
          - "0.0.0.0:5022:5022"
        env:
          LISTEN: ":5000 :5022"
          TALK: "10.0.0.2:80 10.0.0.2:22"
          PRE_RESOLVE: "0"
          VIRTUAL_HOST: "aria2.home.goooseman.ru,aria2-rpc.home.goooseman.ru,plex.home.goooseman.ru,plex-tools.home.goooseman.ru"
          VIRTUAL_PORT: "5000"
          LETSENCRYPT_HOST: "aria2.home.goooseman.ru,aria2-rpc.home.goooseman.ru,plex.home.goooseman.ru,plex-tools.home.goooseman.ru"
      become: yes
      become_user: root

- hosts: home
  vars:
    tincvpn_nodename: home
    tincvpn_destination: cloud
  roles:
    - pi/tinc