- name: Check if Trakt is installed
  stat:
    path: /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle
  register: folder

- name: Create plugins folder
  file:
    path: /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/
    state: directory

- name: Download Trakt
  get_url: 
    url: https://github.com/trakt/Plex-Trakt-Scrobbler/archive/v1.3.3.zip
    dest: /tmp/trakt.zip
  when: folder.stat.exists == False

- name: Unarchive
  unarchive:
    src: /tmp/trakt.zip
    dest: /tmp
    remote_src: yes
  when: folder.stat.exists == False

- name: Move trakt bundle to Plex plugins
  command: mv /tmp/Plex-Trakt-Scrobbler-master/Trakttv.bundle '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle'
  become_user: root
  become: yes
  when: folder.stat.exists == False

- name: Change permissions to plex
  file:
    path: /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/
    state: directory
    recurse: yes
    owner: plex
    group: plex
  become_user: root
  become: yes

- name: Restart service plexmediaserver
  service:
    name: plexmediaserver
    state: restarted
  become_user: root
  become: yes
  when: folder.stat.exists == False 