- name: Install pip3
  apt:
    name: python3-pip
  become_user: root
  become: yes

- name: Install docker-py pip package
  pip:
    name: docker-py
  become_user: root
  become: yes

- name: Create a tinc container
  docker_container:
    name: tinc
    image: "{{ tincvpn_image }}"
    volumes:
      - /etc/tinc:/etc/tinc
    devices:
      - /dev/net/tun
    capabilities:
      - NET_ADMIN
    network_mode: host
    restart: yes
    restart_policy: always
    command: "{{ tincvpn_command }} -D -n {{ tincvpn_network }} -d3"
  become: yes
  become_user: root