- name: Install netatalk
  apt:
    name: netatalk
  become_user: root
  become: yes

- name: Add /media/usb to netatalk
  become_user: root
  become: yes
  lineinfile:
    destfile: /etc/netatalk/AppleVolumes.default
    regexp: '^/media/usb '
    line: '/media/usb                "Network Disk"'
    insertbefore: "^# End of File"
  register: config

- name: Restart service netatalk
  service:
    name: netatalk
    state: restarted
  become_user: root
  become: yes
  when: config.changed