- name: Load chezmoi config file
  slurp:
    src: $HOME/.config/chezmoi/chezmoi.json
  register: chezmoi_json_file

- set_fact:
    chezmoi_json: "{{ chezmoi_json_file.content|b64decode|from_json }}"

- pause:
    prompt: "I need some informartion, so git will save this information in every commit you make. What is your full name?"
  register: git_name
  when: chezmoi_json.data.git.name is not defined

- pause:
    prompt: "What is your email address?"
  register: git_email
  when: chezmoi_json.data.git.email is not defined

- name: Create target directory
  file: path=$HOME/.config/chezmoi state=directory mode=0755

- name: Append git name
  set_fact:
    chezmoi_json: "{{ chezmoi_json | combine({ 'data': {'git': { 'name': git_name.user_input }}})}}"
  when: chezmoi_json.data.git.name is not defined

- name: Append git email
  set_fact:
    chezmoi_json: "{{ chezmoi_json | combine({ 'data': {'git': { 'email': git_email.user_input }}})}}"
  when: chezmoi_json.data.git.email is not defined

- name: Write chezmoi.json
  copy: 
    content: "{{ chezmoi_updated | to_nice_json }}" 
    dest: $HOME/.config/chezmoi/chezmoi.json
  when: chezmoi_json.data.git.email is not defined or chezmoi_json.data.git.name is not defined

- name: run chezmoi apply
  command: chezmoi -v apply
  when: chezmoi_json.data.git.email is not defined or chezmoi_json.data.git.name is not defined
