- name: Install zsh
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - zsh
  become: yes
  become_user: root

- name: Change user shell to zsh
  user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/zsh
  become: yes