- name: Install zsh
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - zsh
  become: yes
  become_user: root

- name: Change user shell to zsh
  become: yes
  become_user: root
  command: chsh -s $(which zsh)