---
galaxy_info:
  author: Nick Pack
  description: "Installs the Android SDK tools, SDKs themselves and applicable application build dependencies"
  company: 0xDEADFA11 Ltd
  license: BSD
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - raring
    - saucy
    - trusty
    - xenial
  - name: Fedora
    versions:
    - 18
    - 22
    - 23
  - name: EL
    versions:
    - 6
    - 7
  - name: MacOSX
    versions:
    - '10.11'
    - '10.12'
  galaxy_tags:
  - development
  - system
  - android
  - adb
dependencies: []
