- name: Enable universe repository (required for fonts-firacode)
  shell: add-apt-repository universe
  become_user: root
  become: yes
  register: command_result
  changed_when: command_result.stdout is not search("is already enabled")

- name: Sublime apt repository key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
  become_user: root
  become: yes

- name: Sublime apt repository
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present
  become_user: root
  become: yes

- name: Docker apt repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become_user: root
  become: yes

- name: Get ubuntu release name
  command: /usr/bin/lsb_release -u -cs
  register: lsb_release
  changed_when: False

- name: Docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable
    state: present
  become_user: root
  become: yes

- name: Etcher apt repository key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 379CE192D401AB61
  become_user: root
  become: yes

- name: Etcher apt repository
  apt_repository:
    repo: deb https://deb.etcher.io stable etcher
    state: present
  become_user: root
  become: yes

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git-flow
    - autojump
    - fonts-firacode
    - sublime-merge
    - sublime-text
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - xclip # For micro
    - balena-etcher-electron
  become_user: root
  become: yes