- name: Install fnm dependencies
  apt:
    name:
      - curl
      - unzip
  become: true
  when: ansible_pkg_mgr == 'apt'

- name: Check if fnm is installed
  stat:
    path: $HOME/.fnm
  register: fnm_folder

- name: Download fnm installer
  get_url:
    url: https://github.com/Schniz/fnm/raw/master/.ci/install.sh
    dest: /tmp/fnm-installer.sh
    mode: +x
  when: fnm_folder.stat.exists == False and ansible_distribution != 'MacOSX'

- name: Execute the fnm-installer.sh
  shell: /tmp/fnm-installer.sh --skip-shell
  when: fnm_folder.stat.exists == False and ansible_distribution != 'MacOSX'

- name: Remove the fnm-installer.sh
  file: path=/tmp/fnm-installer.sh state=absent
  when: fnm_folder.stat.exists == False and ansible_distribution != 'MacOSX'

- name: Install fnm using brew
  homebrew:
    name:
      - Schniz/tap/fnm
    state: present
  when: ansible_distribution == 'MacOSX'

- name: Activate fnm
  shell: eval "`fnm env --multi`"
  when: fnm_folder.stat.exists == False

- name: Check if 10.14 is installed
  shell: "fnm ls | grep '10.14'"
  register: is_installed
  ignore_errors: true
  changed_when: no

- name: Install node 10.14
  shell: fnm install 10.14
  when: is_installed.stdout == ""

- name: Use node 10.14
  shell: fnm use 10.14
  when: is_installed.stdout == ""