- name: Check if fnm is installed
  stat:
    path: $HOME/.fnm
  register: fnm_folder

- name: Download fnm installer
  get_url: url=https://raw.githubusercontent.com/Schniz/fnm/master/.ci/install.sh dest=/tmp/fnm-installer.sh
  when: fnm_folder.stat.exists == False

- name: Execute the fnm-installer.sh
  script: /tmp/fnm-installer.sh --skip-shell
  when: fnm_folder.stat.exists == False

- name: Remove the fnm-installer.sh
  file: path=/tmp/fnm-installer.sh state=absent
  when: fnm_folder.stat.exists == False

- name: Activate fnm
  shell: eval "`fnm env --multi`"
  when: fnm_folder.stat.exists == False

- name: Check if 10.14 is installed
  shell: "$HOME/.fnm/fnm ls | grep '10.14'"
  register: is_installed
  ignore_errors: true
  changed_when: no

- name: Install node 10.14
  shell: $HOME/.fnm/fnm install 10.14
  when: is_installed.stdout == ""

- name: Use node 10.14
  shell: $HOME/.fnm/fnm use 10.14
  when: is_installed.stdout == ""