- name: Create a .desktop entry for android-studio
  copy:
    dest: "/usr/share/applications/android-studio.desktop"
    content: |
      [Desktop Entry]
      Version=1.0
      Type=Application
      Name=Android Studio
      Exec=bash -i "/opt/android-studio/bin/studio.sh" %f
      Icon=/opt/android-studio/bin/studio.png
      Categories=Development;IDE;
      Terminal=false
      StartupNotify=true
      StartupWMClass=jetbrains-android-studio
      Name[en_GB]=android-studio.desktop
  become_user: root
  become: yes
