- name: Pull webui-aria2 image
  docker_image:
    name: goooseman/webui-aria2:arm32v7
  become: yes
  become_user: root
  ignore_errors: true

- name: Check local webui-aria2 image
  shell: docker images 'goooseman/webui-aria2:arm32v7' | grep 'webui-aria2'
  register: check_result
  become: yes
  become_user: root
  ignore_errors: true

- name: Ensures /tmp/webui-aria2/ dir exists
  file:
    path: /tmp/webui-aria2/
    state: directory
  when: not check_result | bool

- name: Download webui-aria2 Dockerfile
  when: not check_result | bool
  git:
    repo: https://github.com/goooseman/webui-aria2.git
    version: patch-1
    dest: /tmp/webui-aria2/
    accept_hostkey: true

- name: Build aria2 docker image
  docker_image:
    path: /tmp/webui-aria2/
    name: goooseman/webui-aria2
    tag: arm32v7
  when: not check_result | bool
  become: yes
  become_user: root

- name: Ensures /home/pi/.aria2/session.txt file exists
  file:
    path: /home/pi/.aria2/session.txt
    state: file

- name: Ensures /home/pi/.aria2/aria2.log file exists
  file:
    path: /home/pi/.aria2/aria2.log
    state: file

- name: Copy aria2 conf file
  copy:
    src: ../assets/aria2.conf
    dest: /home/pi/.aria2/aria2.conf