- name: Pull webui-aria2 image
  docker_image:
    name: goooseman/webui-aria2:arm32v7
  become: yes
  become_user: root
  ignore_errors: true

- name: Check local webui-aria2 image
  shell: docker images 'goooseman/webui-aria2:arm32v7' | grep 'webui-aria2'
  register: is_build
  become: yes
  become_user: root
  ignore_errors: true
  changed_when: no

- name: Ensures /tmp/webui-aria2/ dir exists
  file:
    path: /tmp/webui-aria2/
    state: directory
  when: is_build.stdout == ""

- name: Download webui-aria2 Dockerfile
  when: is_build.stdout == ""
  git:
    repo: https://github.com/goooseman/webui-aria2.git
    version: patch-1
    dest: /tmp/webui-aria2/
    accept_hostkey: true

- name: Build aria2 docker image
  docker_image:
    path: /tmp/webui-aria2/
    name: goooseman/webui-aria2
    dockerfile: Dockerfile.arm32v7
    tag: arm32v7
  when: is_build.stdout == ""
  become: yes
  become_user: root

- name: Ensures /home/pi/.aria2/ dir exists
  file:
    path: /home/pi/.aria2/
    state: directory

- name: Ensures /home/pi/.aria2/session.txt file exists
  copy:
    content: ""
    dest: /home/pi/.aria2/session.txt
    force: no

- name: Ensures /home/pi/.aria2/aria2.log file exists
  copy:
    content: ""
    dest: /home/pi/.aria2/session.txt
    force: no

- name: Copy aria2 conf file 
  copy:
    src: ../assets/aria2.conf
    dest: /home/pi/.aria2/aria2.conf

- name: Create a aria2 container
  docker_container:
    name: webui-aria2
    image: goooseman/webui-aria2:arm32v7
    volumes:
      - /home/pi/.aria2:/home/aria/.aria2
      - /media/usb:/data/downloads
    ports:
      - "6800:6800"
    env:
      VIRTUAL_HOST: aria2.raspberrypi.local
      VIRTUAL_PORT: 8080
    restart_policy: always
  become: yes
  become_user: root

- name: Create a nginx container
  docker_container:
    name: nginx
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
    restart_policy: always
  become: yes
  become_user: root