- name: Load chezmoi config file
  slurp:
    src: $HOME/.config/chezmoi/chezmoi.json
  register: chezmoi_json_file

- set_fact:
    chezmoi_json: "{{ chezmoi_json_file.content|b64decode|from_json }}"

- pause:
    prompt: "Aria2 secret token?"
  register: secret_token
  when: chezmoi_json.data.aria2.secret is not defined

- name: Append secret token
  set_fact:
    chezmoi_json: "{{ chezmoi_json | combine({ 'data': {'aria2': { 'secret': secret_token.user_input }}})}}"
  when: chezmoi_json.data.aria2.secret is not defined
 
- debug:
  var: chezmoi_json

- name: Write chezmoi.json
  copy: 
    content: "{{ chezmoi_json | to_nice_json }}" 
    dest: $HOME/.config/chezmoi/chezmoi.json
  when: chezmoi_json.data.aria2.secret is not defined

- name: run chezmoi apply
  command: chezmoi -v apply
  when: chezmoi_json.data.aria2.secret is not defined