---

- name: Install Android SDKs for applicable releases
  command: "{{ ansible_env.HOME }}/sdk-install.expect"
  # Skip linting here, because I need to implement something more sane for checking pre-installed SDKs
  tags:
    - skip_ansible_lint
